### PR TITLE
SAMD51 I2C slave support for Wire library and SAMD51 viariants.

### LINKED ISSUE #45: M4 I2C as slave
I2C slave on the M4 is not working using the standard sketch:

```
    #include <Wire.h>

    void setup() {
      Wire.begin(8);                // join i2c bus with address #8
      Wire.onReceive(receiveEvent); // register event
      Serial.begin(115200);      // start serial for output
    }

    void loop() {
      delay(50);
    }

    // function that executes whenever data is received from master
    // this function is registered as an event, see setup()
    void receiveEvent(int howMany) {
      Serial.println("active");
      while (1 < Wire.available()) { // loop through all but the last
        char c = Wire.read(); // receive byte as a character
        Serial.print(c);         // print the character
      }
      int x = Wire.read();    // receive byte as an integer
      Serial.println(x);         // print the integer
    }
```
It will lock up the board running the Master sketch. Using an Feather M0 as a slave works fine.

See comments on the Adafruit forum as well: https://forums.adafruit.com/viewtopic.php?f=63&t=135452

### PR DESCRIPTION
**Pull request by JordanMajd**
Fixes #45 by adding handlers for all for SAMD51 SERCOM I2C interrupts to `wire.cpp` and defining them  in the appropriate `variant.h`.

This is opened as a draft, because the M4 Trellis has a conflict as it already defined handlers for SERCOM4 for use with UART `Serial1` in its `variants.cpp`. I'm looking for advice on how to best resolve this.

### CODE REVIEW

File: variants/trellis_m4/variant.cpp [hunk 1]
```diff
@@ -110,21 +110,22 @@ SERCOM sercom3( SERCOM3 ) ;
 SERCOM sercom4( SERCOM4 ) ;
 SERCOM sercom5( SERCOM5 ) ;
 
-Uart Serial1( &sercom4, PIN_SERIAL1_RX, PIN_SERIAL1_TX, PAD_SERIAL1_RX, PAD_SERIAL1_TX ) ;
-
-void SERCOM4_0_Handler()
```
Comment (JordanMajd) [inline variants/trellis_m4/variant.cpp]: Here are the SERCOM4 interrupt handlers defined for UART Serial1.

File: variants/trellis_m4/variant.h [hunk 2]
```diff
@@ -156,6 +156,10 @@ static const uint8_t SCK  = PIN_SPI_SCK ;
 #define PIN_WIRE_SCL         (22u)
 #define PERIPH_WIRE          sercom4
 #define WIRE_IT_HANDLER      SERCOM4_Handler
+#define WIRE_IT_HANDLER_0    SERCOM4_0_Handler
```
Comment (JordanMajd) [inline variants/trellis_m4/variant.h]: Here is where I also defined  the SERCOM4 interrupt handlers.

**Comment by ladyada** [comment]
thank you this is great! i think trellis is the tough one because its a multi-use port

however i think lets keep it for Serial use ... that way it can be used with MIDI which our demos show off. rather than I2C

sound OK?

File: variants/trellis_m4/variant.h [hunk 3]
```diff
@@ -241,5 +250,5 @@ extern Uart Serial1;
 #define SERIAL_PORT_HARDWARE_OPEN   Serial1
 
 
-#endif /* _VARIANT_MERTO_M4_ */
+#endif /* _VARIANT_TRELLIS_M4_ */
```
Comment (ladyada) [inline variants/trellis_m4/variant.h]: oops thanks :)

**Comment by ladyada** [comment]
looks good to me - let me know when the PR is ready for review / merge

**Comment by JordanMajd** [comment]
`Serial1` is back online, should be ready for review.

Keep kicking ass, you are an inspiration.

**Comment by JordanMajd** [comment]
`Serial1` is back online, should be ready for review.

Keep kicking ass, you are an inspiration.

**Comment by ladyada** [comment]
oh one more request, is there an example you used in Wire library to test? if it isnt already there please add the test sketch!

**Comment by JordanMajd** [comment]
Tested with existing examples connected to an Uno running the corresponding master/slave example:

- `slave_receiver`, `slave_sender` to verify I2C slave operations.
- `master_writer`, `master_reader` to verify I2C existing master functionality.

Additionally tested `slave_sender` against a Pi CM3 running `i2cdetect -y <bus> <address>` and `i2cget -y <bus> <address>`

**Comment by JordanMajd** [comment]
In case it slipped by, I was only able to extensively test on an ItsyBitsy M4 and the Trellis M4 when Serial1 was disabled.  Definitely worth testing on other hardware.

**Comment by ladyada** [comment]
tested a feather m4 successfully - you're a hero @JordanMajd  :)

**Comment by ladyada** [comment]
@JordanMajd hi please take a look at https://forums.adafruit.com/viewtopic.php?f=62&t=159769 if you have any suggestions for this person!

**Comment by JordanMajd** [comment]
*rolls d20*

Yep, I'll look into it tonight.

**Comment by ladyada** [comment]
:D thank u!
